/* 컴활 2급 개념카드: 지식, 판별 기준, 기출 연결 규칙 */
window.BWR_CONCEPTS = [
  {id:"grid",subject:"computer",term:"그리드 컴퓨팅",definition:"지리적으로 떨어진 여러 컴퓨터의 자원을 연결해 하나의 고성능 컴퓨터처럼 활용하는 분산 처리 방식입니다.",criterion:"필요한 만큼 서비스를 빌려 쓰면 클라우드, 여러 지역의 계산 자원을 한 작업에 묶으면 그리드입니다.",mistake:"클라우드·분산 컴퓨팅이라는 말만 보고 고르지 말고 자원을 ‘서비스로 이용’하는지 ‘공동 계산에 결합’하는지 확인합니다.",match:{any:["그리드 컴퓨팅","그리드컴퓨팅"]}},
  {id:"cmos",subject:"computer",term:"CMOS",definition:"시스템 날짜와 시간, 부팅 순서, 전원 관리, PnP 같은 기본 하드웨어 설정값을 보관합니다.",criterion:"설정값을 저장하는 곳은 CMOS, 전원을 켤 때 장치를 검사하는 과정은 POST, 입출력 기본 명령을 제공하는 것은 BIOS입니다.",mistake:"CMOS를 검사 프로그램이나 펌웨어 자체로 오해하기 쉽습니다. 문제에서 ‘설정 저장’인지 ‘부팅 검사’인지 먼저 구분합니다.",match:{any:["CMOS"]}},
  {id:"ipv6",subject:"computer",term:"IPv6",definition:"128비트 주소를 16진수와 콜론(:)으로 표현하는 차세대 인터넷 주소 체계입니다.",criterion:"IPv4는 32비트·10진수·점, IPv6는 128비트·16진수·콜론입니다. 연속된 0은 주소에서 한 번만 ::로 줄입니다.",mistake:"비트 수와 표기법을 서로 바꾸어 놓은 보기가 자주 나옵니다. ‘128·16진수·콜론’을 한 묶음으로 판단합니다.",match:{any:["IPv6","IPV6"]}},
  {id:"bridge",subject:"computer",term:"브리지",definition:"같은 프로토콜을 사용하는 두 LAN을 연결하고 MAC 주소를 기준으로 프레임을 전달하는 장비입니다.",criterion:"리피터는 신호 재생, 브리지는 LAN 구간 연결, 라우터는 IP 경로 선택, 게이트웨이는 서로 다른 체계의 변환·출입구 역할입니다.",mistake:"네트워크 장비를 모두 ‘연결 장치’로 외우면 틀립니다. 판단 단위를 신호·프레임·IP 경로·프로토콜 변환으로 나눕니다.",match:{any:["브리지(Bridge)","브리지"]}},
  {id:"morphing",subject:"computer",term:"모핑",definition:"두 이미지나 3차원 모델 사이의 중간 형태를 생성해 한 대상이 다른 대상으로 부드럽게 변하게 하는 기법입니다.",criterion:"형태가 변하면 모핑, 주요 장면 사이를 보간하면 트위닝, 정지 인형을 조금씩 촬영하면 클레이메이션입니다.",mistake:"단순 이동이나 프레임 보간을 형태 변형과 혼동하지 않습니다. 문제의 핵심 동사가 ‘변한다’인지 ‘움직인다’인지 봅니다.",match:{any:["모핑","Morphing"]}},
  {id:"shareware",subject:"computer",term:"셰어웨어",definition:"기능이나 사용 기간을 제한해 먼저 공개하고 시험 사용 뒤 구매를 유도하는 소프트웨어입니다.",criterion:"무료 사용·배포가 중심이면 프리웨어, 제한된 시험 사용이면 셰어웨어, 오류 수정용 일부 파일이면 패치입니다.",mistake:"인터넷에서 무료로 내려받았다는 사실만으로 프리웨어를 고르면 안 됩니다. 사용 기간·기능 제한 여부가 기준입니다.",match:{any:["셰어웨어","Shareware"]}},
  {id:"restore",subject:"computer",term:"시스템 복원",definition:"복원 지점을 사용해 Windows 시스템 파일과 설정을 이전 상태로 되돌리는 기능입니다.",criterion:"시스템 설정과 설치 프로그램 변화는 되돌릴 수 있지만 개인 문서 백업이나 삭제 파일 복구 기능은 아닙니다.",mistake:"‘복원’이라는 이름 때문에 모든 파일이 돌아온다고 생각하기 쉽습니다. 대상이 시스템 상태인지 개인 데이터인지 구분합니다.",match:{any:["시스템 복원","복원 지점"]}},
  {id:"ransomware",subject:"computer",term:"랜섬웨어",definition:"파일을 암호화하거나 시스템 사용을 막고 복구 대가로 금전을 요구하는 악성 프로그램입니다.",criterion:"자기 복제는 웜, 정보 몰래 수집은 스파이웨어, 키 입력 탈취는 키로거, 접근 차단과 금전 요구는 랜섬웨어입니다.",mistake:"악성코드라는 공통점보다 최종 행동을 봅니다. ‘암호화·잠금·금전 요구’가 함께 나오면 랜섬웨어입니다.",match:{any:["랜섬웨어","Ransomware"]}},
  {id:"pop3",subject:"computer",term:"POP3",definition:"원격 메일 서버에 접속해 받은 메일을 사용자 컴퓨터로 가져오는 수신 프로토콜입니다.",criterion:"메일 보내기는 SMTP, 서버에서 수신 메일 가져오기는 POP3, 서버에 둔 채 동기화하면 IMAP입니다.",mistake:"SMTP와 POP3를 메일 프로토콜이라는 이유로 바꾸어 고르기 쉽습니다. 방향을 ‘보냄·받음’으로 먼저 판단합니다.",match:{any:["POP3"]}},
  {id:"repeater",subject:"computer",term:"리피터",definition:"통신 선로에서 약해지거나 왜곡된 디지털 신호를 증폭·재생해 다시 전달하는 물리 계층 장비입니다.",criterion:"신호 세기를 복원하면 리피터, 프레임을 걸러 LAN을 잇으면 브리지, 최적 IP 경로를 고르면 라우터입니다.",mistake:"전송 거리를 늘린다는 표현과 경로를 선택한다는 표현을 구분합니다. 리피터는 주소를 해석해 길을 고르지 않습니다.",match:{any:["리피터(Repeater)","리피터"]}},
  {id:"ascii",subject:"computer",term:"ASCII",definition:"표준 ASCII는 7비트로 영문 대소문자, 숫자, 문장 부호와 제어 문자를 표현하는 문자 코드입니다.",criterion:"표준 ASCII는 7비트 128개 문자이고, 추가 1비트는 통신 시 패리티나 확장 문자에 사용될 수 있습니다.",mistake:"저장 단위가 1바이트라는 설명 때문에 표준 코드도 8비트라고 판단하지 않습니다. 표준과 확장 ASCII를 구분합니다.",match:{any:["ASCII"]}},
  {id:"vector",subject:"computer",term:"벡터 그래픽",definition:"점·선·곡선의 위치와 관계를 수학적 정보로 저장해 이미지를 표현하는 방식입니다.",criterion:"수학적 도형 정보면 벡터, 픽셀의 색상 정보면 비트맵입니다. 벡터는 확대에 강하고 비트맵은 사진 표현에 유리합니다.",mistake:"모든 벡터 파일이 항상 작다고 단정하지 않습니다. 시험에서는 확대 시 계단 현상과 표현 단위를 우선 판단합니다.",match:{any:["벡터 그래픽","벡터 방식","벡터 이미지"]}},
  {id:"alt-enter",subject:"spreadsheet",term:"Alt + Enter",definition:"Excel 셀에 데이터를 입력하는 중 같은 셀 안에서 강제로 줄을 바꾸는 바로 가기 키입니다.",criterion:"Enter는 입력 완료와 아래 셀 이동, Ctrl+Enter는 선택 영역 동시 입력, Alt+Enter는 한 셀 내부 줄 바꿈입니다.",mistake:"입력 완료 후 셀 이동과 셀 안에서 줄을 바꾸는 동작을 혼동하지 않습니다. 문제에서 ‘같은 셀 안’이 핵심입니다.",match:{any:["Alt> + <Enter","Alt+Enter","Alt] + [Enter","Alt + Enter"]}},
  {id:"vlookup",subject:"spreadsheet",term:"VLOOKUP",definition:"범위의 첫 번째 열에서 값을 찾고 지정한 열 번호의 같은 행 값을 반환하는 함수입니다.",criterion:"정확히 일치하려면 네 번째 인수에 FALSE 또는 0, 근삿값이면 TRUE 또는 1을 사용하며 근삿값 범위는 정렬이 필요합니다.",mistake:"찾을 값이 범위 첫 열에 있어야 한다는 조건과 열 번호가 범위 안에서 센 상대 번호라는 점을 자주 놓칩니다.",match:{any:["VLOOKUP"]}},
  {id:"consolidate",subject:"spreadsheet",term:"데이터 통합",definition:"여러 범위의 데이터를 위치 또는 항목 이름 기준으로 모아 합계·평균·개수 등으로 요약하는 기능입니다.",criterion:"여러 원본 범위를 하나로 요약하면 통합, 한 목록 안에서 그룹별 계산은 부분합, 조건별 결과 비교는 시나리오입니다.",mistake:"‘요약’이라는 말만 보고 부분합을 고르지 않습니다. 원본이 여러 범위인지 하나의 정렬된 목록인지 확인합니다.",match:{any:["데이터 통합","통합 대화상자"]}},
  {id:"sheet-protection",subject:"spreadsheet",term:"시트 보호와 잠금",definition:"셀의 잠금 속성은 시트 보호를 적용했을 때 실제 편집 제한으로 작동합니다.",criterion:"입력을 허용할 셀은 잠금을 먼저 해제하고, 나머지 셀은 잠금 상태로 둔 뒤 시트를 보호합니다.",mistake:"셀에 잠금 속성만 지정했다고 바로 편집이 막히는 것은 아닙니다. 마지막에 시트 보호를 적용해야 효력이 생깁니다.",match:{any:["시트 보호","셀의 잠금","잠금 해제"]}},
  {id:"format-placeholders",subject:"spreadsheet",term:"표시 형식 0 · # · ?",definition:"0은 없는 자리도 0으로 표시하고, #은 유효한 숫자만 표시하며, ?는 숫자가 없어도 자리만 확보합니다.",criterion:"강제 표시 0, 불필요한 0 생략 #, 자릿수 정렬용 공백 ?로 목적을 나누어 판단합니다.",mistake:"#이 숫자가 없을 때 0을 표시한다는 보기가 대표 함정입니다. ‘자리 확보’와 ‘0 표시’를 구분합니다.",match:{any:["사용자 지정 표시 형식","사용자 정의 표시 형식","표시 형식에서"],all:["#"]}},
  {id:"wildcards",subject:"spreadsheet",term:"와일드카드 * · ?",definition:"*는 길이에 관계없는 여러 문자, ?는 임의의 한 문자를 대신하는 검색 기호입니다.",criterion:"문자 수를 정확히 한 자리만 허용하면 ?, 0개 이상 여러 문자를 허용하면 *를 사용합니다.",mistake:"?를 ‘한 글자 이상’으로 외우면 틀립니다. 정확히 한 글자라는 제한과 *의 가변 길이를 비교합니다.",match:{any:["와일드카드","삼?주식회사","임의의 한 문자"]}},
  {id:"date-serial",subject:"spreadsheet",term:"날짜·시간 일련번호",definition:"Excel은 날짜를 기준일부터 센 정수, 시간을 하루를 1로 본 소수로 저장하며 표시 형식만 날짜·시간으로 보여 줍니다.",criterion:"날짜·시간의 내부 값은 숫자이므로 계산할 수 있고 기본적으로 오른쪽 정렬됩니다. 표시 형식 변경은 값 자체를 바꾸지 않습니다.",mistake:"화면에 날짜로 보인다는 이유로 텍스트라고 판단하지 않습니다. 입력값의 저장 형식과 화면 표시를 분리합니다.",match:{any:["날짜와 시간 데이터","날짜 데이터","날짜·시간","날짜의 일련번호"]}},
  {id:"goal-seek",subject:"spreadsheet",term:"목표값 찾기",definition:"수식 결과가 원하는 값이 되도록 그 수식이 참조하는 하나의 입력 셀 값을 역으로 계산하는 도구입니다.",criterion:"하나의 결과와 하나의 변경 셀을 역산하면 목표값 찾기, 여러 입력 조합을 저장·비교하면 시나리오입니다.",mistake:"변경 셀에는 수식이 아니라 조정 가능한 입력값이 있어야 합니다. 여러 변수를 동시에 찾는 기능으로 오해하지 않습니다.",match:{any:["목표값 찾기"]}},
  {id:"advanced-filter",subject:"spreadsheet",term:"고급 필터 조건",definition:"복잡한 조건 범위를 별도로 작성해 목록을 필터링하거나 다른 위치에 결과를 복사하는 기능입니다.",criterion:"조건 범위에서 같은 행은 AND, 서로 다른 행은 OR이며 필드명은 원본 목록의 필드명과 정확히 같아야 합니다.",mistake:"일상 언어의 줄바꿈과 논리 관계를 반대로 생각하기 쉽습니다. 한 행에서 동시에 만족하면 AND로 기억합니다.",match:{any:["고급 필터"]}},
  {id:"rank-eq",subject:"spreadsheet",term:"RANK.EQ",definition:"목록에서 지정한 값의 순위를 구하며 같은 값에는 같은 순위를 부여하는 함수입니다.",criterion:"세 번째 인수가 0 또는 생략이면 큰 값이 1위인 내림차순, 1이면 작은 값이 1위인 오름차순입니다.",mistake:"정렬 방향 인수를 반대로 외우거나 복사할 참조 범위를 고정하지 않는 실수가 많습니다. 순위 기준 범위는 보통 절대 참조합니다.",match:{any:["RANK.EQ","RANK(","RANK 함수"]}},
  {id:"pivot",subject:"spreadsheet",term:"피벗 테이블",definition:"많은 데이터를 행·열·필터·값 필드로 재배치해 원하는 관점으로 요약하고 분석하는 도구입니다.",criterion:"원본 데이터는 유지한 채 요약 배치를 바꾸며, 원본이 변경되면 새로 고침해야 결과에 반영됩니다.",mistake:"피벗 테이블을 삭제하거나 필드를 옮겨도 원본 데이터가 삭제되는 것은 아닙니다. 원본과 요약 결과를 분리합니다.",match:{any:["피벗 테이블","피벗테이블"]}},
  {id:"countif-average",subject:"spreadsheet",term:"COUNTIF + AVERAGE",definition:"AVERAGE로 기준값을 구하고 COUNTIF의 조건 문자열과 &로 연결하면 평균 이상·이하 값의 개수를 셀 수 있습니다.",criterion:"비교 연산자는 문자열 안에 쓰고 계산된 기준값은 &로 결합합니다. 예: =COUNTIF(C2:C8,\">=\"&AVERAGE(C2:C8)).",mistake:"\">=AVERAGE(...)\" 전체를 문자열로 쓰면 함수가 계산되지 않습니다. 연산자 문자열과 함수 결과의 경계를 구분합니다.",match:{all:["COUNTIF","AVERAGE"]}}
];

window.BWR_CONCEPT_MATCH = (concept, question) => {
  if (concept.subject && question.subject !== concept.subject) return false;
  const haystack = [question.q, ...(question.c || []), question.e].join(" ").toLowerCase();
  const any = concept.match?.any || [];
  const all = concept.match?.all || [];
  const exclude = concept.match?.exclude || [];
  const hasAny = !any.length || any.some((term) => haystack.includes(String(term).toLowerCase()));
  const hasAll = all.every((term) => haystack.includes(String(term).toLowerCase()));
  const hasExcluded = exclude.some((term) => haystack.includes(String(term).toLowerCase()));
  return hasAny && hasAll && !hasExcluded;
};
